### ISSUE TITLE
Bluetooth stopped working after wake from sleep

### ISSUE THREAD

**Issue by lorda** [laserb/gnome-shell-extension-suspend-button#38]
After installing Suspend Button my Bluetooth stopped working.

I reinstalled bluez [following the instructions in this post](https://ar.al/2018/07/29/fix-for-no-bluetooth-found-error-after-wake-from-sleep/) but it didn't work.

**Comment by laserb** [comment]
Please try disabling the extension and see if that solves your issue.

I am pretty sure that your issue is not related to the extension. It basically just re-arranges the buttons and does nothing related to bluetooth.

It sounds like a common bluetooth issue. Did you try restarting the bluetooth service? Something like "systemctl restart bluetooth" should do it. From my experience sometimes only a shutdown and cold boot solves such issues.

**Comment by lorda** [comment]
Thanks for your answer.

I disabled it and uninstalled it. No change.

I guess the problem is related to the wake from sleep and not the extension.

I reinstalled the bluetooth service and also tried systemctl restart bluetooth but it did not fix the problem. Thanks for your help. I will close this issue, [I created a post on Ask Ubuntu](https://askubuntu.com/questions/1137916/bluetooth-stopped-working-after-wake-from-sleep).
